sudo: required
dist: trusty
language: python
python:
  - "2.7"
env:
  - PYBOSSA_SETTINGS='../settings_test.py' PYBOSSA_REDIS_CACHE_DISABLED='1'
services:
  - redis-server
addons:
  postgresql: "9.3"
before_install:
  - sudo apt-get update -y && sudo apt-get install -y swig libffi-dev
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - git clone --recursive https://github.com/PyBossa/pybossa.git
  - pip install -r pybossa/requirements.txt
  - pip install --editable pybossa
  - pip install pep8
before_script:
  - redis-server --version
  - pip --version
  - redis-server pybossa/contrib/redis/sentinel.conf --sentinel
  - psql -c "create user rtester with createdb login password 'rtester'" -U postgres
  - psql -c "create database pybossa_test owner rtester encoding 'UTF-8' lc_collate 'en_US.UTF-8' lc_ctype 'en_US.UTF-8' template template0;" -U postgres
script:
  - alembic -c pybossa/alembictest.ini stamp head
  - alembic -c pybossa/alembictest.ini upgrade head
  - nosetests -d tests/
  - pep8
after_success:
  - pip install coveralls
  - coveralls
